var    gulp = require ('gulp'),
  del = require('del'),
    concat =require('gulp-concat'),
   min =require('gulp-uglify'),
   size =require('gulp-size'),
   sourcemaps =require('gulp-sourcemaps'),
   browser =require("browser-sync").create(),
  bootstrap =require('bootstrap'),
  sass =require('gulp-sass');